/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class JFrameValeriano extends javax.swing.JFrame {

    /**
     * Creates new form JFrameValeriano
     */
    public JFrameValeriano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome01 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIdade01 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome02 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIdade02 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome03 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIdade03 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome01");

        jLabel2.setText("Idade01");

        jLabel3.setText("Nome02");

        jLabel4.setText("Idade02");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome03");

        jLabel6.setText("Idade03");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNome01)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldIdade01)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNome02)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldIdade02, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)))
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNome03)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldIdade03))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldIdade01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNome02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldIdade02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldIdade03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        String Nome01, Nome02, Nome03;
        
        int Idade01, Idade02, Idade03 ;
        
        Idade01 = Integer.parseInt(jTextFieldIdade01.getText());
        Idade02 = Integer.parseInt(jTextFieldIdade02.getText());
        Idade03 = Integer.parseInt(jTextFieldIdade03.getText());
        
        Nome01 = (jTextFieldNome01.getText());
        Nome02 = (jTextFieldNome02.getText());
        Nome03 = (jTextFieldNome03.getText());
       
        boolean tipoBooleano = false ;
        
        if (Idade01 >= 21) {
            
            tipoBooleano = true ;  
        }
        
       if (tipoBooleano == true) {
        
           System.out.println("Bem vindo" + Nome01 + "Ao exercito");
           
       } else{
           System.out.println("Voce não e bem vindo" + Nome01 + "Ao exercito");
       }
   

       
       if (Idade02 >= 21) {
            
        tipoBooleano = true ;  
    }
        
       if (tipoBooleano == true) {
        
           System.out.println("Bem vindo" + Nome02 + "Ao exercito");
           
       } else{
           System.out.println("Voce não e bem vindo" + Nome02 + "Ao exercito");
       }
            
       
       if (Idade03 >= 21) {
            
        tipoBooleano = true ;  
        }
        
       if (tipoBooleano == true) {
        
           System.out.println("Bem vindo" + Nome03 + "Ao exercito");
           
       } else{
           System.out.println("Voce não e bem vindo" + Nome03 + "Ao exercito");
       }
            
            



    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameValeriano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameValeriano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameValeriano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameValeriano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameValeriano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldIdade01;
    private javax.swing.JTextField jTextFieldIdade02;
    private javax.swing.JTextField jTextFieldIdade03;
    private javax.swing.JTextField jTextFieldNome01;
    private javax.swing.JTextField jTextFieldNome02;
    private javax.swing.JTextField jTextFieldNome03;
    // End of variables declaration                   
}